FROM phpmyadmin/phpmyadmin:latest

# Setup PHP
RUN echo 'memory_limit = 1G' >> /usr/local/etc/php/php.ini
RUN echo 'post_max_size = 1G' >> /usr/local/etc/php/php.ini
RUN echo 'upload_max_filesize = 1G' >> /usr/local/etc/php/php.ini
